name: Automatically approve and merge safe dependency updates
on:
- pull_request_target
permissions:
  contents: write
  pull-requests: write
jobs:
  auto-merge-safe-deps:
    uses: jenkins-infra/github-reusable-workflows/.github/workflows/auto-merge-safe-deps.yml@791f6a10b7e9084eb9d6742293df4a562a801a8d # v1
